# Generated by Django 4.0.3 on 2022-04-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snackname', models.CharField(max_length=50)),
                ('snackbrand', models.CharField(max_length=100)),
                ('snackprice', models.IntegerField(default=0)),
                ('producer', models.CharField(max_length=100)),
                ('stockunit', models.CharField(max_length=10)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
